version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: gear_picker
    volumes:
      - db_volume:/var/lib/mysql
    ports:
      - "3308:3306"
volumes:
  db_volume:
